### ISSUE TITLE
properties in parent pom

### ISSUE THREAD

**Issue by dealboy** [joinfaces/joinfaces-example#57]
Hello,
doing a mvn package , I get the following error: 

```
Some problems were encountered while building the effective model for org.joinfaces:joinfaces-example:jar:2.2.0-SNAPSHOT
'reporting.plugins.plugin.version' for org.apache.maven.plugins:maven-project-info-reports-plugin is missing. @ org.joinfaces:jsf-spring-boot-parent:2.2.0, C:\Users\yannis\.m2\repository\org\joinfaces\jsf-spring-boot-parent\2.2.0\jsf-spring-boot-parent-2.2.0.pom, line 596, column 21
```

I suppose the property is to be picked by spring-boot-parent, but it is failing for me. Any ideas?

cheers
Yannis

**Comment by persapiens** [comment]
Hello @dealboy ,

    I've just created the project with no problems. I've erased my local maven repository to force download all artifacts again.

    Are you behind any maven proxy?
    Which maven version do you use?

You are welcome

**Comment by dealboy** [comment]
something with my proxy was wrong, thanks for the quick reply, sorry for the false alarm

**Comment by pvy** [comment]
I had same problem to build the example project.

In addition, I found this line in log:
`
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
Detected Maven Version: 3.0.5 is not in the allowed range 3.1.1.
`

After maven upgrade, everything is ok.
